# Generated by Django 5.1.7 on 2025-07-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Defender', 'Defender'), ('Challenger', 'Challenger')], default='Challenger', help_text='Defender (existente) o Challenger (potencial)', max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('criticality_ranking', models.FloatField(blank=True, help_text='Ranking de criticidad', null=True)),
                ('availability', models.FloatField(blank=True, help_text='Disponibilidad (%)', null=True)),
                ('date_in_service', models.DateField(blank=True, help_text='Fecha de puesta en servicio', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra', max_digits=20, null=True)),
                ('installation_and_training_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de instalación y formación', max_digits=20, null=True)),
                ('setup_costs', models.DecimalField(blank=True, decimal_places=2, help_text='Costos de configuración inicial', max_digits=20, null=True)),
                ('current_resale_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de reventa actual', max_digits=20, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor residual o de rescate', max_digits=20, null=True)),
                ('annual_maintenance_labor_parts', models.DecimalField(blank=True, decimal_places=2, help_text='Mantenimiento anual (mano de obra y piezas)', max_digits=20, null=True)),
                ('initial_monthly_maintenance_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de mantenimiento mensual inicial', max_digits=20, null=True)),
                ('maintenance_cost_gradient', models.FloatField(blank=True, help_text='Gradiente de costo de mantenimiento (aumento mensual)', null=True)),
                ('cost_of_downtime', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de tiempo de inactividad ($/h)', max_digits=20, null=True)),
                ('operator_labor_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de mano de obra del operador ($/h)', max_digits=20, null=True)),
                ('energy_consumption', models.FloatField(blank=True, help_text='Consumo de energía (kWh/h)', null=True)),
                ('energy_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de energía ($/kWh)', max_digits=20, null=True)),
                ('consumable_replacement_cost_1', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de reemplazo de consumible 1', max_digits=20, null=True)),
                ('consumable_lifespan_1', models.FloatField(blank=True, help_text='Vida útil del consumible 1 (en unidades)', null=True)),
                ('useful_life', models.IntegerField(blank=True, help_text='Vida útil (en meses)', null=True)),
                ('end_of_useful_life_date', models.DateField(blank=True, help_text='Fecha de fin de vida útil', null=True)),
                ('monthly_depreciation', models.DecimalField(blank=True, decimal_places=2, help_text='Depreciación mensual', max_digits=20, null=True)),
                ('production_rate', models.FloatField(blank=True, help_text='Tasa de producción', null=True)),
                ('production_rate_units', models.CharField(blank=True, help_text='Ej: piezas/hora, litros/min', max_length=50, null=True)),
                ('texas_workdays', models.IntegerField(blank=True, help_text="Días de trabajo (según estándar 'Texas')", null=True)),
                ('monthly_operating_hours', models.FloatField(blank=True, help_text='Horas de operación mensuales', null=True)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
    ]
