# Generated by Django 5.1.7 on 2025-07-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='annual_maintenance_labor_parts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Mantenimiento Anual (Mano de Obra y Piezas)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='availability',
            field=models.FloatField(blank=True, null=True, verbose_name='Disponibilidad (%)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='consumable_lifespan_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Vida Útil del Consumible (unidades)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='consumable_replacement_cost_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo de Reemplazo de Consumible'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='cost_of_downtime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo de Inactividad ($/h)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='criticality_ranking',
            field=models.FloatField(blank=True, null=True, verbose_name='Ranking de Criticidad'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='current_resale_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor de Reventa Actual'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='date_in_service',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Puesta en Servicio'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='end_of_useful_life_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de Vida Útil'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='energy_consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumo de Energía (kWh/h)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='energy_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo de Energía ($/kWh)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='initial_monthly_maintenance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Mensual Inicial de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='installation_and_training_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo de Instalación y Formación'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='maintenance_cost_gradient',
            field=models.FloatField(blank=True, null=True, verbose_name='Aumento Mensual del Costo de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='monthly_depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Depreciación Mensual'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='monthly_operating_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas de Operación Mensuales'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Máquina'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='operator_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo de Mano de Obra del Operador ($/h)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='production_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de Producción'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='production_rate_units',
            field=models.CharField(blank=True, help_text='Ej: piezas/hora', max_length=50, null=True, verbose_name='Unidades de Tasa de Producción'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Residual'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='setup_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costos de Configuración'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='texas_workdays',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días de Trabajo (Texas)'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('Defender', 'Defender'), ('Challenger', 'Challenger')], default='Challenger', help_text='Defender (existente) o Challenger (potencial)', max_length=15, verbose_name='Tipo de Máquina'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='useful_life',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida Útil (meses)'),
        ),
    ]
