# Generated by Django 5.1.7 on 2025-07-04 00:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_maquina_annual_maintenance_labor_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
