# Generated by Django 5.1.7 on 2025-07-08 14:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_maquina_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('terminos_contractuales', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Términos Contractuales (días)')),
                ('average_days_to_pay', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días Promedio de Pago Real')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Proveedor')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('terminos_pago', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Términos de Pago (días)')),
                ('tipo_materia_prima', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Materia Prima')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Registro')),
                ('fecha_entrega_cliente', models.DateField(verbose_name='Fecha Entrega Cliente')),
                ('valor_cobrar_cliente', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor a Cobrar')),
                ('fecha_limite_cobro', models.DateField(verbose_name='Fecha Límite Cobro')),
                ('valor_pagado_cliente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Pagado')),
                ('fecha_pago_cliente', models.DateField(blank=True, null=True, verbose_name='Fecha Pago Cliente')),
                ('estado_cobro', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado_parcial', 'Pagado Parcial'), ('pagado_total', 'Pagado Total')], default='pendiente', max_length=20, verbose_name='Estado Cobro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Obligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obligacion', models.CharField(max_length=50, verbose_name='ID Obligación')),
                ('valor_pagar', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor a Pagar')),
                ('fecha_esperada_entrega', models.DateField(verbose_name='Fecha Esperada Entrega')),
                ('fecha_recepcion_real', models.DateField(blank=True, null=True, verbose_name='Fecha Recepción Real')),
                ('fecha_limite_pago', models.DateField(verbose_name='Fecha Límite Pago')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor', verbose_name='Proveedor')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to='core.registro', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Obligación',
                'verbose_name_plural': 'Obligaciones',
                'ordering': ['fecha_esperada_entrega'],
                'unique_together': {('registro', 'id_obligacion')},
            },
        ),
    ]
