# Generated by Django 5.1.7 on 2025-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_proveedor_registro_obligacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligacion',
            name='pagos_realizados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='obligacion',
            name='valor_pagado_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='registro',
            name='pagos_recibidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
