# Generated by Django 5.1.7 on 2025-07-09 15:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_obligacion_pagos_realizados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligacion',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='obligacion',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='obligacion',
            name='pagos_realizados',
        ),
        migrations.RemoveField(
            model_name='obligacion',
            name='valor_pagado_total',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='fecha_pago_cliente',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='pagos_recibidos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='valor_pagado_cliente',
        ),
        migrations.AddField(
            model_name='obligacion',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado_parcial', 'Pagado Parcial'), ('pagado_total', 'Pagado Total')], default='pendiente', max_length=20, verbose_name='Estado Pago'),
        ),
        migrations.CreateModel(
            name='PagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='transferencia', max_length=50, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cliente', to='core.registro', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='transferencia', max_length=50, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_proveedor', to='core.obligacion', verbose_name='Obligación')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
