# Generated by Django 5.1.7 on 2025-07-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_pagoproveedor_obligacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_limite_cobro',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha Límite Cobro'),
        ),
    ]
