# Generated by Django 5.1.7 on 2025-07-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_registro_fecha_limite_cobro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contacto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='city',
            field=models.CharField(default='NaN', max_length=100, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
