# Generated by Django 5.1.7 on 2025-07-25 20:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cliente_contacto_cliente_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_materia_prima',
        ),
        migrations.AddField(
            model_name='maquina',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo de Adquisición (para Defender)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='book_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor en Libros'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='equipment_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Equipo'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='machine_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad de la Máquina (años)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='average_days_to_pay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días Promedio de Pago Real'),
        ),
        migrations.CreateModel(
            name='AnalisisComparativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_analisis', models.CharField(max_length=200, verbose_name='Nombre del Análisis')),
                ('wacc', models.DecimalField(decimal_places=4, default=0.14, max_digits=5, verbose_name='WACC (Costo Promedio Ponderado de Capital)')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.21, max_digits=5, verbose_name='Tasa de Impuestos')),
                ('financing_rate', models.DecimalField(decimal_places=2, default=7.5, max_digits=5, verbose_name='Tasa de Financiamiento (%)')),
                ('financing_months', models.IntegerField(default=60, verbose_name='Meses de Financiamiento')),
                ('pv_defender', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Presente Defender')),
                ('eac_defender', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='EAC Defender')),
                ('pv_challenger', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Presente Challenger')),
                ('eac_challenger', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='EAC Challenger')),
                ('recomendacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recomendación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_como_challenger', to='core.maquina')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_como_defender', to='core.maquina')),
            ],
            options={
                'verbose_name': 'Análisis Comparativo',
                'verbose_name_plural': 'Análisis Comparativos',
            },
        ),
        migrations.CreateModel(
            name='FlujoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('Defender', 'Defender'), ('Challenger', 'Challenger')], max_length=15)),
                ('año', models.IntegerField(verbose_name='Año')),
                ('cash_flow_bruto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Flujo de Caja Bruto')),
                ('depreciacion', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Depreciación')),
                ('tax_shield', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Escudo Fiscal')),
                ('after_tax_cash_flow', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Flujo de Caja Después de Impuestos')),
                ('present_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Presente')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos_caja', to='core.analisiscomparativo')),
            ],
            options={
                'verbose_name': 'Flujo de Caja',
                'verbose_name_plural': 'Flujos de Caja',
                'unique_together': {('analisis', 'tipo_equipo', 'año')},
            },
        ),
        migrations.CreateModel(
            name='TablaAmortizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('balance_inicial', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Balance Inicial')),
                ('pago_mensual', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pago Mensual')),
                ('pago_principal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pago a Principal')),
                ('pago_interes', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pago de Interés')),
                ('balance_final', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Balance Final')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla_amortizacion', to='core.analisiscomparativo')),
            ],
            options={
                'verbose_name': 'Tabla de Amortización',
                'verbose_name_plural': 'Tablas de Amortización',
                'unique_together': {('analisis', 'mes')},
            },
        ),
    ]
