# Generated by Django 5.1.7 on 2025-07-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_proveedor_tipo_materia_prima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='activo',
        ),
    ]
